amazon/urls.py
from django.urls import path
from amazon.views import *
app_name='amazon'

urlpatterns=[
    path('asus/',asus,name='asus'),
]

flipkart/urls.py
from django.urls import path
from flipkart.views import *

app_name='flipkart'

urlpatterns=[
    path('asus/',asus,name='asus'),
]

project10/urls.py
from django.contrib import admin
from django.urls import path,include
import amazon,flipkart

urlpatterns = [
    path('admin/', admin.site.urls),
    path('amazon/',include('amazon.urls')),
    path('flipkart/',include('flipkart.urls')),

]

amazon/models.py
from django.db import models

# Create your models here.

flipkart/models.py
from django.db import models

# Create your models here.

amazon/views.py
from django.shortcuts import render

def asus(request):
    asus={'brand':'ASUS','model': 'VIVOBOOK 15 PRO', 'processor': 'RYZEN 7', 'gpu':'RTX 3050TI','cost':'1,50,000'}
    return render(request,'amazon.html',asus)

flipkart/views.py
from django.shortcuts import render


def asus(request):
    asus={'brand':'ASUS','model': 'VIVOBOOK 15 PRO', 'processor': 'RYZEN 7', 'gpu':'RTX 3050TI','cost':'1,40,000'}
    return render(request,'flipkart.html',asus)

templates/amazon.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Amazon</title>
</head>
<body>
    <h1>Amazon</h1>
    <center>
        <h1>Laptop Brand : {{brand}}</h1>
        <h1>Model : {{model}}</h1>
        <h1>Processor : {{processor}}</h1>
        <h1>GPU : {{gpu}}</h1>
        <h1>Cost : {{cost}}</h1>
        <a href="{% url 'flipkart:asus'%}">Check Price in Flipkart</a>
    </center>
</body>
</html>

templates/flipkart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flipkart</title>
</head>
<body>
    <h1>Flipkart</h1>
    <center>
        <h1>Laptop Brand : {{brand}}</h1>
        <h1>Model : {{model}}</h1>
        <h1>Processor : {{processor}}</h1>
        <h1>GPU : {{gpu}}</h1>
        <h1>Cost : {{cost}}</h1>
        <a href="{% url 'amazon:asus'%}">Check Price in Amazon</a>
    </center>
</body>
</html>